# Default values for load-users.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: dictybase/modware-user
  tag: 0.0.1
  pullPolicy: IfNotPresent
# Keys for accessing data in s3(minio) storage
#s3:
  #accessKey:
  #secretKey:
