apiVersion: v1
description: A Helm chart for Kubernetes to run user api server.
name: user-api-server
version: 2.0.0
sources:
  - https://hub.docker.com/r/dictybase/modware-user
  - https://github.com/dictyBase/modware-user
maintainers:
  - name: Siddhartha Basu
    email: siddhartha-basu@northwestern.edu
appVersion: 0.3.0
